NumPy (Numerical Python) is a fundamental library for scientific computing in Python. It provides support for large, multi-dimensional arrays and matrices, along with a collection of mathematical functions to operate on them efficiently.



In [ ]:
import numpy as np

arr1 =  np.array([1, 2, 3, 4, 5])
print(arr1, type(arr1)) #N- dimensoinal array

[1 2 3 4 5] <class 'numpy.ndarray'>


In [12]:
# 2D array
arr2 = np.array([[1, 2, 3], [4, 5, 6]])
print(arr2, arr2.shape)

[[1 2 3]
 [4 5 6]] (2, 3)


In [21]:
arr3 = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(arr3, arr3.shape) # 3D array

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]] (2, 2, 3)


In [16]:
array1 = np.zeros((3, 3))       # 3x3 array of zeros
array2 =  np.ones((2, 2))        # 2x2 array of ones
array3 =  np.full((2, 2), 7)     # 2x2 array filled with 7
array4 =  np.eye(4)              # Identity matrix of size 4x4
array5 = np.random.rand(3, 3)   # Random numbers between 0 and 1
array6 =  np.arange(1, 10, 2)    # [1, 3, 5, 7, 9] - Similar to range()
array7 = np.linspace(1, 10, 5)  # 5 evenly spaced numbers from 1 to 10


In [ ]:
print(array1)


[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [38]:
print(array5)
print(array4)

[[0.86227815 0.83459658 0.08508207]
 [0.83035674 0.53743123 0.92723487]
 [0.13677354 0.09297047 0.9059503 ]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [ ]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print("Array:", arr)
print("Shape:", arr.shape)  # Shape of the array [rows, columns]
print("Size:", arr.size)    # Number of elements in the array
print("Data type:", arr.dtype) # Data type of the elements in the array
print("Dimension:", arr.ndim) # Number of dimensions
print("Item size:", arr.itemsize)   # Size of each element in bytes

Array: [[1 2 3 4]
 [5 6 7 8]]
Shape: (2, 4)
Size: 8
Data type: int64
Dimension: 2
Item size: 8


Mathematical Operations

In [42]:
# element wise operations
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print(a + b)  # [5, 7, 9]
print(a * b)  # [4, 10, 18]
print(a / b)  # [0.25, 0.4, 0.5]
print(a ** 2) # [1, 4, 9]
print(np.sqrt(a))

[5 7 9]
[ 4 10 18]
[0.25 0.4  0.5 ]
[1 4 9]
[1.         1.41421356 1.73205081]


Aggregrate operations

In [24]:
arr = np.array([[1,2,3],[4,5,6]])
mean = np.mean(arr)
print(mean)

3.5


In [25]:
standard_deviation = np.std(arr)
print(standard_deviation)

1.707825127659933


In [28]:
# All the row elements are summed up
row_sum = np.sum(arr, axis=1) # for colums axis=0
column_sum = np.sum(arr, axis=0)
print(row_sum, column_sum)

[ 6 15] [5 7 9]


In [ ]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

[[1 2]
 [3 4]] [[5 6]
 [7 8]]


In [31]:
print(np.dot(A, B)) # Matrix multiplication

[[19 22]
 [43 50]]


In [ ]:
print(np.linalg.det(A)) # Determinant of a matrix
print(np.linalg.inv(A)) # Inverse of a matrix

-2.0000000000000004
[[-2.   1. ]
 [ 1.5 -0.5]]


In [36]:
print(np.linalg.eig(A)) # Eigenvalues and eigenvectors of a matrix

EigResult(eigenvalues=array([-0.37228132,  5.37228132]), eigenvectors=array([[-0.82456484, -0.41597356],
       [ 0.56576746, -0.90937671]]))


In [44]:
transpose = np.transpose(A)
print(transpose)

[[1 3]
 [2 4]]


In [48]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print("Stacked Vertically\n", np.vstack((a, b)))  # Stack vertically
print("Stacked horizontally\n",np.hstack((a, b)))  # Stack horizontally


Stacked Vertically
 [[1 2 3]
 [4 5 6]]
Stacked horizontally
 [1 2 3 4 5 6]


In [51]:
arr = np.array([1, 2, 3, 4, 5, 6])
print(np.split(arr, 2))  # (arr, size of each split)


[array([1, 2, 3]), array([4, 5, 6])]


In [ ]:
given_arr =  np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(np.split(given_arr, [1, 2]))  # Split after the first and the second row

[array([[1, 2, 3]]), array([[4, 5, 6]]), array([[7, 8, 9]])]


In [ ]:
arr = np.linspace(1, 10, 100)
print(arr) # 100 evenly spaced numbers between 1 and 10

[ 1.          1.09090909  1.18181818  1.27272727  1.36363636  1.45454545
  1.54545455  1.63636364  1.72727273  1.81818182  1.90909091  2.
  2.09090909  2.18181818  2.27272727  2.36363636  2.45454545  2.54545455
  2.63636364  2.72727273  2.81818182  2.90909091  3.          3.09090909
  3.18181818  3.27272727  3.36363636  3.45454545  3.54545455  3.63636364
  3.72727273  3.81818182  3.90909091  4.          4.09090909  4.18181818
  4.27272727  4.36363636  4.45454545  4.54545455  4.63636364  4.72727273
  4.81818182  4.90909091  5.          5.09090909  5.18181818  5.27272727
  5.36363636  5.45454545  5.54545455  5.63636364  5.72727273  5.81818182
  5.90909091  6.          6.09090909  6.18181818  6.27272727  6.36363636
  6.45454545  6.54545455  6.63636364  6.72727273  6.81818182  6.90909091
  7.          7.09090909  7.18181818  7.27272727  7.36363636  7.45454545
  7.54545455  7.63636364  7.72727273  7.81818182  7.90909091  8.
  8.09090909  8.18181818  8.27272727  8.36363636  8.45454545  8.545

In [58]:
arr =  np.array([[10,  20, 30, 40, 50]])
normalized_arr =   (arr-arr.min())/(arr.max()-arr.min())
print(normalized_arr)

[[0.   0.25 0.5  0.75 1.  ]]
